#DB 공통 설정
spring:
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    tomcat:
      max-wait: 3000
      max-active: 10
      max-idle: 10
      min-idle: 10
      initial-size: 10

---
spring:
  profiles: local
  datasource:
    url: "jdbc:mariadb://localhost:3306/task?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul"
    username: "ENC(9kUHFtgwrErZsADUhFQCTw==)"
    password: "ENC(rGr4LdD0nt0AUlrNEwyL7w==)"

---