#DB 공통 설정
spring:
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"

---
spring:
  profiles: local
  datasource:
    url: "jdbc:mariadb://localhost:3306/task?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul"
    username: "root"
    password: "123456"

---